version: "3.9"

services:
  app:
    image: purawatzero/dpu_ct519_lab5:img_golang
    container_name: ctn_golang
    ports:
      - "8080:8080"
    restart: unless-stopped
    expose:
      - 8080
    volumes:
      - ./www:/go/src/www
      - ./:/go/src
    working_dir: /go/src/
    command: 'go run main.go'